<h1 style="color:white;text-align:center;background-color: black;"> Heading 1: Numpy Arrays Creation in Methods </h1>

In [1]:
import numpy as np

<h2 style="color:green;text-align:center;background-color:white;"> 1.Using Python DataStructures - Lists, Tuples, Sets </h2>

<b> Using Lists </b>

In [2]:
List1 = [1,35,634,565,345,24.4]
list_arr1 = np.array(List1) 
print('list_arr1 : ',list_arr1, 'it is of datatype ',list_arr1.dtype)

#output: list_arr1 :  [  1  35 634 565 345 234] it is of datatype  float64


list_arr1 :  [  1.   35.  634.  565.  345.   24.4] it is of datatype  float64


<b> Using Tuples </b>

In [3]:
Tuple1 = tuple(List1)
tuple_arr1 = np.array(Tuple1) 
print('tuple_arr1 : ',tuple_arr1, 'it is of datatype ',tuple_arr1.dtype)

#output: tuple_arr1 :  [  1  35 634 565 345 234] it is of datatype  float64


tuple_arr1 :  [  1.   35.  634.  565.  345.   24.4] it is of datatype  float64


<b> Using Sets</b>

In [4]:
Set1 = tuple(List1)
Set1 = np.array(Set1) 
print('Set_Array1 : ',Set1, 'it is of datatype ',Set1.dtype)

#output: Set_Array1 :  [  1  35 634 565 345 234] it is of datatype  float64


Set_Array1 :  [  1.   35.  634.  565.  345.   24.4] it is of datatype  float64


<b> Heterogenous datatype Arrays would be created as unicode/object </b>

In [5]:
List2 = [1,'shafi', 23,345.23,45]

# since list2 has heterogenous(different) datatype, it would create an "object array" instead of int array
list_arr = np.array(List2) 
print(list_arr, 'it is of datatype ',list_arr.dtype)


['1' 'shafi' '23' '345.23' '45'] it is of datatype  <U32


<h2 style="color:green;text-align:center;background-color:white;"> 2. Using NumPy Array Creation Functions</h2>

<b> Using np.arange() Function:</b>
 creates arrays with regularly incrementing values

In [6]:
np.arange(10) # O/P; array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(2, 10, dtype=float) # O/P: array([2., 3., 4., 5., 6., 7., 8., 9.])

np.arange(2, 3, 0.1) #O/P: array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])


array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

<b> Using np.linspace() :</b> np.linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [7]:
np.linspace(1., 4., 6) # [1. , 1.6, 2.2, 2.8, 3.4, 4. ]
np.linspace(12, 20, 4) # [12., 14.66666667, 17.33333333, 20.]

array([12.        , 14.66666667, 17.33333333, 20.        ])

<b> Using np.eye(n, m) : </b> np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:

In [8]:
np.eye(3)
# O/P: array([[1., 0., 0.],
#       [0., 1., 0.],
 #      [0., 0., 1.]])
    
    
np.eye(3, 5)
# O/P:array([[1., 0., 0., 0., 0.],
#       [0., 1., 0., 0., 0.],
#       [0., 0., 1., 0., 0.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

<b> Using np.zeros() : </b> numpy.zeros will create an array filled with 0 values with the specified shape. The default dtype is float64:

In [9]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

<b> Using np.ones : </b> numpy.ones will create an array filled with 1 values. It is identical to zeros in all other respects as such:

In [10]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

<h2 style="color:Green;text-align:center;background-color:white;">  3. Using np.random Module : </h2>

In [11]:
np.random.rand(3,2)

array([[0.42478587, 0.63215241],
       [0.83924158, 0.14111225],
       [0.64619111, 0.81872962]])

In [12]:
np.random.randint(5, size=(2, 4)) # Generate a 2 x 4 array of ints between 0 and 4, inclusive:

array([[4, 4, 4, 4],
       [2, 3, 2, 3]])

<h1 style="color:white;text-align:center;background-color: black;">Heading 2: Attributes of Numpy Array</h1>

<b> Shape:</b> Shape gives the number of elements in each dimension in tuple format.



In [13]:
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.shape # 2rows and 3 columns

(2, 3)

<b> Reshape():</b> Reshaping means changing the shape of an array.



In [15]:
a.reshape(3,2) # converting to 3rows, 2columns

array([[1, 2],
       [3, 4],
       [5, 6]])

<b> ndim:</b> ndim gives the number of dimension in tuple format.



In [16]:
b = np.arange(24)  # 1Dimensional 24rows and 1 Column
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
a.ndim # 2 dimension
b.ndim # 1 dimension

1

In [18]:
c = b.reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
c.ndim 

3

<b> size:</b> size gives the number of elements present in Numpy Array (rows * columns * dimensions)


In [20]:
c
#   array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]],

#        [[12, 13, 14, 15],
#         [16, 17, 18, 19],
#         [20, 21, 22, 23]]])
c.size

24

<b> itemsize:</b> itemsize gives size of one array element in bytes.



In [21]:
c.itemsize #4 bytes

4

<b> dtype:</b> dtype gives the datatype of array 


In [22]:
c.dtype #int32 

dtype('int32')

<h1 style="color:white;text-align:center;background-color: black;">  Heading 3: Methods of Numpy Array </h1>

<p style="color:Black;text-align:left;font-weight: bold;">  1. Axes of Numpy Array : </p>
a)  Axis =0 (Row-wise): considers all the values of all rows but only single column <br>
b)  Axis =1 (Column-wise ): considers all the values of all columns but only single row


In [23]:
a=np.array([[1,3],[2,4]])
a

array([[1, 3],
       [2, 4]])

<p style="color:Black;text-align:left;font-weight: bold;"> sum(): </p> returns sum of values at the prescribed axis

In [24]:
#sum : array, row-wise, column-wise
print(a.sum(),a.sum(axis=0),a.sum(axis=1))

10 [3 7] [4 6]


<p style="color:Black;text-align:left;font-weight: bold;"> array.T : </p> converts rows to columns and vice-versa (Transpose)

In [25]:
#Transpose
a.T

array([[1, 2],
       [3, 4]])

In [26]:
#sum of Transpose of Matrix : array, row-wise, column-wise
print(a.T.sum(),a.T.sum(axis=0),a.T.sum(axis=1))

10 [4 6] [3 7]


In [27]:
a

array([[1, 3],
       [2, 4]])

<p style="color:Black;text-align:left;font-weight: bold;"> min(): </p> Returns Min values for the prescribed axis, returns min value of the whole array if axis is not mentioned.

In [28]:
#Min value  : array, row-wise, column-wise
print(a.min(),a.min(axis=0),a.min(axis=1))

1 [1 3] [1 2]


In [29]:
a=np.array([[3,4],[2,1]])
a

array([[3, 4],
       [2, 1]])

<p style="color:Black;text-align:left;font-weight: bold;"> argmin(): </p> Returns <b>Index of Min</b> values for the prescribed axis, returns <b>index of min</b> value of the whole array if axis is not mentioned.

In [30]:
#Min value Index number  : array, row-wise, column-wise
print(a.argmin(),a.argmin(axis=0),a.argmin(axis=1))

3 [1 1] [0 1]


<p style="color:Black;text-align:left;font-weight: bold;"> nonzero(): </p> Returns the indices of non zero values in a tuple of rows/columns 

In [31]:
a.nonzero()

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

<p style="color:Black;text-align:left;font-weight: bold;"> count_nonzero(): </p> Returns the count of non zero values as per the prescribed axis

In [32]:
i = np.eye(3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

np.count_nonzero(i,axis=1)

array([1, 1, 1], dtype=int64)

<p style="color:Black;text-align:left;font-weight: bold;"> ravel(): </p>converts multi-dimensional Array to single dimensional Array(1D)

In [33]:
print("normal Array: \n"        ,i,
      "\nand ravel is : \n"   ,i.ravel())

normal Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
and ravel is : 
 [1. 0. 0. 0. 1. 0. 0. 0. 1.]


In [34]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

<p style="color:Black;text-align:left;font-weight: bold;"> swapaxes(): </p> similar to transpose , converts rows to columns and vice-versa

In [35]:
x.swapaxes(2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

<p style="color:Black;text-align:left;font-weight: bold;">  2. Some Basic Array Calculations : </p>

In [36]:
a
# array([[3, 4],
#        [2, 1]])


b =np.array([[5,7],[6,8]])

# array([[5, 7],
#        [6, 8]])


In [37]:
#sum
a+b
# array([[ 8, 11],
#        [ 8,  9]])

#subtraction
a-b
# array([[-2, -3],
#        [-4, -7]])

# a to the power of 4
a**4
# array([[ 81, 256],
#        [ 16,   1]]


b
# array([[5, 7],
#        [6, 8]])
c=b.copy()
c
# array([[5, 7],
#        [6, 8]])

array([[5, 7],
       [6, 8]])

In [38]:
#weighted average 
data=range(1,11)
wt=range(10,0,-1)
np.average(data, weights=wt) # (range*weight) / weight



4.0

<p style="color:Black;text-align:left;font-weight: bold;">  Iterate using nditerate(): </p>

In [39]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [40]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [41]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#### Joining two arrays

In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [43]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
#using stack function;
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


#### hstack() - vstack() - dstack():

In [45]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [46]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


#### array_split()

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [49]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


#### where()

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


#### sort():

In [52]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [53]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Written by [Shafi Mohiddin Shaik]( https://www.linkedin.com/in/shafi-s-0279651b0/)
> [Refer Numpy Documentation](https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html)